//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 12/11/2013 23:04:33
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Subsonic8.ErrorDialog
{
    using System;

    using Windows.ApplicationModel.Resources;
    
    
    public partial class ErrorDialogViewModelStrings
    {
        
        private static ResourceLoader resourceLoader;
        
        static ErrorDialogViewModelStrings()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(ErrorDialogViewModelStrings).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            try
            {
                resourceLoader = new ResourceLoader("ErrorDialogViewModelStrings");
            }
            catch(Exception)
            {
                resourceLoader = new ResourceLoader(currentAssemblyName + "/ErrorDialogViewModelStrings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Please send this email to: {0}"
        /// </summary>
        public static string ActionInformation
        {
            get
            {
                return resourceLoader.GetString("ActionInformation");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "You can choose to send us a report with the error details or ignore this (sending the report by email will allow us to fix the issue as fast as we can)."
        /// </summary>
        public static string DefaultMessage
        {
            get
            {
                return resourceLoader.GetString("DefaultMessage");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "There was a problem resolving the given domain name. Please check that you typed the domain name correctly."
        /// </summary>
        public static string DnsIssue
        {
            get
            {
                return resourceLoader.GetString("DnsIssue");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "The error details have been successfully deilvered."
        /// </summary>
        public static string ErrorDelivered
        {
            get
            {
                return resourceLoader.GetString("ErrorDelivered");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "subsonic8@agilefreaks.com"
        /// </summary>
        public static string ErrorReportDeliveryEmail
        {
            get
            {
                return resourceLoader.GetString("ErrorReportDeliveryEmail");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "The error details could not be successfully deilvered."
        /// </summary>
        public static string ErrorWasNotDelivered
        {
            get
            {
                return resourceLoader.GetString("ErrorWasNotDelivered");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "It seems that you are trying to connect to a server which uses https but has an invalid certificate. To be able to connect to this server you must ensure that it has a valid certificate or that the validation of it's certificate is successfull on this computer (this usually means adding the certificate's certification authority to your trusted root certification authorities list)."
        /// </summary>
        public static string HttpsIssue
        {
            get
            {
                return resourceLoader.GetString("HttpsIssue");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "If you think this is an issue with this app please feel free to contact us by email at subsonic8@agilefreaks.com or using the buttons at the bottom of the screen and we'll gladly help you out. "
        /// </summary>
        public static string KnownErrorMessage
        {
            get
            {
                return resourceLoader.GetString("KnownErrorMessage");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "It seems that the server address you typed in is wrong (the server responded with not found). Please make sure you type in the full address to your subsonic server as you would in your browser."
        /// </summary>
        public static string NotFoundIssue
        {
            get
            {
                return resourceLoader.GetString("NotFoundIssue");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "An error occured with the following message:"
        /// </summary>
        public static string Notice
        {
            get
            {
                return resourceLoader.GetString("Notice");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Could not complete request."
        /// </summary>
        public static string TitleMessage
        {
            get
            {
                return resourceLoader.GetString("TitleMessage");
            }
        }
    }
}
