//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 11/18/2013 16:35:14
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Subsonic8.ArtistInfo
{
    using Windows.ApplicationModel.Resources;
    
    
    public partial class ArtistInfoViewModelStrings
    {
        
        private static ResourceLoader resourceLoader;
        
        static ArtistInfoViewModelStrings()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(ArtistInfoViewModelStrings).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (executingAssemblyName.Equals(currentAssemblyName))
            {
                resourceLoader = new ResourceLoader("ArtistInfoViewModelStrings");
            }
            else
            {
                resourceLoader = new ResourceLoader(currentAssemblyName + "/ArtistInfoViewModelStrings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Could not connect to data provider. Please try again later."
        /// </summary>
        public static string CouldNotFetchData
        {
            get
            {
                return resourceLoader.GetString("CouldNotFetchData");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "No biography found."
        /// </summary>
        public static string NoBiographyFound
        {
            get
            {
                return resourceLoader.GetString("NoBiographyFound");
            }
        }
    }
}
