//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 07/27/2015 20:54:42
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace Subsonic8.Shell
{
    using System;

    using Windows.ApplicationModel.Resources;
    
    
    public partial class ShellStrings
    {
        
        private static ResourceLoader resourceLoader;
        
        static ShellStrings()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(ShellStrings).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            try
            {
                resourceLoader = new ResourceLoader("ShellStrings");
            }
            catch(Exception)
            {
                resourceLoader = new ResourceLoader(currentAssemblyName + "/ShellStrings");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "You did not set up your connection. Please fill in you server address, username and password to start browsing."
        /// </summary>
        public static string NotConfigured
        {
            get
            {
                return resourceLoader.GetString("NotConfigured");
            }
        }
    }
}
